---
abstract: 'Provides installation and config information for SWIG'
author:
  - 'Jason McManus <infidel AT cpan.org>'
build_requires:
  Archive::Extract: 0
  ExtUtils::MakeMaker: 0
  Getopt::Long: 0
  HTTP::Tiny: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-SWIG
provides:
  Alien::SWIG:
    file: lib/Alien/SWIG.pm
    version: 0.02_02
requires:
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02_02
